### ISSUE TITLE
Improve QT5 support

### ISSUE THREAD

**Issue by hphilm** [manjaro/boxit#10]
**boxit-server** seems to be broken in functionality when using **qt5**. **boxit-client** throws following errors when compiled with **qt5**:

```
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
```

**Comment by guinux** [comment]
"qmake-qt5 && make all" works fine for me. Just qt5-base installed.

**Comment by hphilm** [comment]
It works fine for compiling, however it has no function. **boxit-client** has issues with **QSocketNotifier** and the **server** doesn't allow you to connect. **boxit** itself was coded based on **qt4**.

**Comment by hphilm** [comment]
@Kirek: do you have an idea on how we hide the `QSocketNotifier` messages? Seems to be a "feature" of QT5. Compiling the same source with QT4 we don't have these messages.

**Comment by Kirek** [comment]
When this error happens actually? Always or when uploading files? It breaks boxit or its just an annoying message?

**Comment by hphilm** [comment]
It is just an annoying message. It happens when the packages get synced from the Arch-Repos.

**Comment by Kirek** [comment]
Not sure if it will help, can you try this patch? https://gist.github.com/Kirek/d073372ab5e310b68abcfa0c2ee1c4b5

**Comment by rahmanshaber** [comment]
it build fine and no problems .full qt5 installed .no qt4 package in system.
found no QSocketNotifier declaration .i recommend declaration.
see this issue [here](https://stackoverflow.com/questions/20051224/qt-socket-notifiers-cannot-be-enabled-from-another-thread)

**Comment by hphilm** [comment]
So far @Kirek's patch works as it should. Will test it a little more before closing this.

**Comment by Kirek** [comment]
https://gist.github.com/Kirek/2e227ce1b44a7f18d589c99283f32a37

Same patch but cleaning things up.

**Comment by hphilm** [comment]
@Kirek: I've tested now several situtations with **boxit**. I'm pretty sure your second patch does the job.

**Comment by Kirek** [comment]
https://github.com/manjaro/boxit/commit/5eb226d6651dfb5c83b5649e4e3c2447b6ec5b61 reopen if necessary
