### ISSUE TITLE
port BoxIT to manjaro-arm

### ISSUE THREAD

**Issue by hphilm** [manjaro/boxit#6]
I started to port **boxit** to [manjaro-arm](https://github.com/manjaro/boxit/tree/manjaro-arm). Somehow I'm not able to sync from **archlinuxarm.org mirrors**. Maybe it is a server configuration issue ...

**Comment by Strit** [comment]
archlinuxarm.org does not have an rsync server running, so you can't initiate a sync from them, they have to "push" a sync out to you.

That's very annoying, but it's reality. So I guess, we would have to make a script, using wget/curl or something to pull the packages from alarm.

**Comment by hphilm** [comment]
This was dropped a while ago. They used their own management tool.
