### ISSUE TITLE
Add support for *.files

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/boxit#7]
Manjaro repos lack the proper *.files for pkgfile to work. These can be easily generated with normal repo-add command. I noticed that the repo-add script in this repo is at least 90 lines shorter than the normal one. Would it be possible to update the repo-add script so that it would generate the *.files?

**Comment by hphilm** [comment]
We are currently working on it: https://github.com/manjaro/boxit/commit/67b8a8c8fadc154706cacbbfb00ba8a784d5d64a
